### PR TITLE
PitDroid Updates

### PR DESCRIPTION
**Pull request by wbhinton**
Converted the project from Eclipse to Android Studio. 
Updated for compatibility up to Android M. 
Changed some text, nothing major though.

### CODE REVIEW

**Comment by colings** [comment]
Try getting latest and see if it fixes your issues.  If not, submit a patch against latest and I can add it in.

**Comment by wbhinton** [comment]
I don't see an APK to try.

I fixed the issues I was having and got it working on my N6, N7, and N9
with the latest builds from Android.


*Weston Hinton*
Mobile: 903.617.7388
Office: 855.762.3637

**Comment by colings** [comment]
Well, I didn't post an apk since you forked the code I figured you'd just pull latest and try it yourself. I'm not sure what you mean when you say it was fixed by the latest builds from Android.

-----Original Message-----

**Comment by wbhinton** [comment]
I will try to compile the new project in Android studio and will let you
know how it turns out. I have a busy weekend, but will try it out this
coming week.

In my last msg I was just letting you know that I have gotten pitdroid to
work with the N5, N6, N7 and N9 with Android 5.1.1 using the modified
eclipse project I imported to android studio.

*Weston Hinton*
Mobile: 903.617.7388
Office: 855.762.3637

**Comment by wbhinton** [comment]
Everything is working on my end.

Thanks

*Weston Hinton*
Mobile: 903.617.7388
Office: 855.762.3637

**Pull request closed without merging**
